
server:
    port: 9999

spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        ddl-auto: create-drop
        username: pizza-user
        password: pizza-pass
